# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 10:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 30 characters or fewer.', max_length=30, verbose_name='Service Name')),
                ('request_host', models.UUIDField(help_text='Resource Host, to be passed to kong', unique=True, verbose_name='Request Host')),
                ('upstream_url', models.URLField(help_text='Required. 200 characters or fewer.', verbose_name='upstream url of service.')),
                ('swagger_schema', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Swagger Client')),
                ('is_public', models.BooleanField(default=False, help_text='If checked , this service will be publicly available for use.', verbose_name='Make Service Public')),
                ('created_at', models.DateTimeField(db_index=True, editable=False, verbose_name='created at')),
                ('modified_at', models.DateTimeField(db_index=True, editable=False, verbose_name='modified at')),
            ],
            options={
                'verbose_name_plural': 'Services Vault',
                'ordering': ['-created_at'],
                'verbose_name': 'Service Vault',
            },
        ),
    ]
