# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevault',
            name='request_host',
            field=models.CharField(help_text='Resource Host, to be passed to kong', max_length=200, unique=True, verbose_name='Request Host'),
        ),
    ]
