# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-24 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_vault', '0002_auto_20170323_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevault',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='servicevault',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='servicevault',
            name='name',
            field=models.CharField(help_text='Required. 30 characters or fewer.', max_length=30, unique=True, verbose_name='Service Name'),
        ),
    ]
