# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_vault', '0003_auto_20170324_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevault',
            name='assign_to_user',
            field=models.BooleanField(default=False, help_text='If checked , this service will be enabled for users and will displayed in his services .', verbose_name='Assign this service to User'),
        ),
        migrations.AddField(
            model_name='servicevault',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='This UUID will uniquely identify every registered service.', unique=True, verbose_name='Service UUID.'),
        ),
        migrations.AlterField(
            model_name='servicevault',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at'),
        ),
    ]
