# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_vault', '0004_auto_20170425_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicevault',
            name='assign_to_user',
        ),
        migrations.AddField(
            model_name='servicevault',
            name='assign_to_organization',
            field=models.BooleanField(default=False, help_text='If checked , this service will be enabled for organization and will displayed in his services .', verbose_name='Assign this service to Organization'),
        ),
    ]
