# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_vault', '0005_auto_20170425_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicevault',
            name='assign_to_organization',
        ),
    ]
